### ISSUE TITLE
Delete device feature

### ISSUE THREAD

**Issue by dennisurtubia** [willianrod/ODeck#10]
Hi, @willianrod. I want to suggest a request 😄.

A button to delete a device in the `Start` component, something like this:
![image](https://user-images.githubusercontent.com/33161939/197352801-1c29c664-6c76-4f35-a4a7-91702d037084.png)

I think this device delete action may have some rules, e.g some cascade deletion with keys and pages. So, if this feature make sense for you, a description to done this task might be helpful. Also, I can implement this feature :)

**Comment by willianrod** [comment]
Hi @dennisurtubia, this is a really cool feature. I would suggest to add a confirmation modal first, just to prevent the user deleting a device by accident.
