### ISSUE TITLE
Cannot use comma for hotkey

### ISSUE THREAD

**Issue by Rickamykazy** [willianrod/ODeck#19]
## Expected Behavior

Use comma for hotkey without any issues

## Current Behavior

Press hotkey with Comma key binding and nothing happens. 

## Steps to Reproduce

1. Drag hotkey to the deck

2. Start Recoding 

3. Press Comma key 

4. Hit Save 

5. Press the hotkey in your deck

6. Nothing happens.

## Your Environment

- ODeck version or branch : 0.0.4
- Operating System and version : Windows

**Comment by willianrod** [comment]
Thanks for opening the issue, I came across this issue once and completly forgot about it. This is happening for all commands without any modifiers [ctrl, shift, alt...] I'll work on this one

**Comment by Rickamykazy** [comment]
I forgot to put in the post, but when a was testing different possibility I try to use just the dot key, with and without modifiers, and apparently it worked fine and both ways. I try use modifiers with comma too, but not work unfortunately.

**Comment by willianrod** [comment]
Fixed at https://github.com/willianrod/ODeck/pull/22. Will be available on version v0.0.5
