### ISSUE TITLE
Salvar / Remover e "sair/limpar" o campo da ação

### ISSUE THREAD

**Issue by guilhermeemanuell** [willianrod/ODeck#2]

**Comment by guilhermeemanuell** [comment]
Ao salvar ou remover um botão, a label continua preenchida. Para uma pessoa que esteja tendo um primeiro contato com softwares desse tipo, talvez possa gerar uma certa dúvida, se ela não reparar no preview da página que de fato foi removido o botão.

Seria possível adicionar uma função para que ao remover um botão, os rótulos voltem ao estado inicial (todos limpos)?
E talvez ao salvar, vá para um botão "limpo"? A ser configurado ainda, talvez.

![salvar-apagar-limpar-o-campo](https://user-images.githubusercontent.com/71149993/155145295-16f4d7ed-bfc9-4d39-a5a3-f1a09c835e6b.jpg)

**Comment by willianrod** [comment]
Alteração feita no PR #3 e será lançada na v0.0.2 em breve
