### ISSUE TITLE
Linux Support for Dashboard

### ISSUE THREAD

**Issue by EduardoJM** [willianrod/ODeck#23]
Is Linux Support a priority? is someone working on Linux support for the dashboard?

**Comment by willianrod** [comment]
Our priority is Windows because is the platform most of our users will be using, but we could at least support Linux. The basic features should work fine there

**Comment by EduardoJM** [comment]
> Our priority is Windows because is the platform most of our users will be using

This is a good answer. 

And about the at leat support linux, currently, i use, in most part of time, a linux distro. In the next days i will try to execute it on linux and test the most part of the features of the application

**Comment by Curicows** [comment]
I`m running the application in linux (ubuntu) and it`s working without any issues

**Comment by EduardoJM** [comment]
> Im running the application in linux (ubuntu) and it`s working without any issues

Yes, i'm running on an Linux Mint and is ok. Working on the #33, i will add an release version of the linux application today

**Comment by EduardoJM** [comment]
Closing this issue due the workflow automation and new releases with Linux support.
