### ISSUE TITLE
Add GitHub Actions to deploy the app automatically on every new tag

### ISSUE THREAD

**Issue by willianrod** [willianrod/ODeck#29]
Today the process of deploying is manual, and we should change that. To do that we should use GitHub actions that will be triggered on new tag. 

For now, we should focus on continuously deploying the electron app, because the mobile app will be listed in the App Store/Google Play in the near future.

**Comment by EduardoJM** [comment]
Tonight i made some tests in a private repository and i concluded that i really can create this feature, as we had talked into the PR #24 discussion. Can you assign me?

An brief question about this issue is: for now, we can release the Windows and the Mac OS versions of the electron app?

**Comment by willianrod** [comment]
@EduardoJM assigned. Thanks again ;)
