### ISSUE TITLE
[feature] allow to reorder keys in a page

### ISSUE THREAD

**Issue by willianrod** [willianrod/ODeck#34]
## Description
When creating my page, sometimes I found myself in need to move one existing key to another position. Right now, this is not possible and would be really cool to have this feature. 

## Requirements
- When clicking and dragging an existing key and moving around, a "ghost" element following the cursor should appear
- When dropping the key, you should validate if the target is not already occupied. If not, then update the dragging key to the new position

**Comment by EduardoJM** [comment]
Hi @willianrod,

can i work on this issue?

**Comment by willianrod** [comment]
For sure. I'll assign you
