### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by ZANdewanai** [willianrod/ODeck#55]
havent seen updates yet even though there are a bunch of pull request ready to implement with nice improvements

**Comment by ZANdewanai** [comment]
also hotkeys for numpad would be nice, instead of them being bundled with the normal numbers

**Comment by willianrod** [comment]
Hi @ZANdewanai, it is being worked on but I just haven't had enough free time to work in this project lately, I've been working 12hrs a day and I'm destroyed on weekends. I'll see if I can get some free time this weekend
